name = "StructMethods"
uuid = "caa289c9-0d94-4b40-94da-d515277500b5"
version = "0.2.1"
authors = ["Ashley Trowell <ashley.trowell@matrixresearch.com>"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.9.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
